server:
  port: 8081

spring:
  datasource:
    username: root
    password: 1q2w3e
#    password: test1234
    url: jdbc:mysql://localhost:3306/digitalculture?useUnicode=true&userSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 10MB
      # 单个文件的最大值
      max-file-size: 10MB

msg:
  process:
    ip: localhost

#showSql
logging:
  level:
    com:
      example:
        mapper : debug