server:
  port: 8081

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    username: root
    password: 1q2w3e
#    password: test1234
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&userSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 10MB
      # 单个文件的最大值
      max-file-size: 10MB

#showSql
logging:
  level:
    com:
      example:
        mapper : debug